builds:
  - binary: prestd
    main: ./cmd/prestd/main.go
    ldflags: -s -w main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X github.com/prest/prest/helpers.PrestVersionNumber={{.Version}}
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mipsle
      - mips64le
      - ppc64
      - ppc64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: netbsd
        goarch: arm64
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
      - prestd
    image_templates:
      - "prest/prest:{{ .Tag }}"
      - "prest/ptest:v{{ .Major }}"
      - "prest/prest:latest"
    extra_files:
      - ./cmd/prestd/prest.toml
# release:
#  github:
#    owner: prest
#    name: prest
