sudo: required

language: go

os:
    - linux

go:
    - 1.6
    - 1.7
    - tip

services:
    - postgresql

env:
   - PREST_PG_USER=postgres PREST_PG_DATABASE=prest PREST_PG_PORT=5432

before_install:
   - go get -u github.com/kardianos/govendor
   - govendor sync

before_script:
    - psql -c 'create database prest;' -U postgres
    - psql prest -c 'create table test(name text);' -U postgres

script:
    - go test -v -race ./...
