sudo: required

language: go

os:
    - linux

go:
    - 1.6
    - 1.7

services:
    - postgresql

env:
   - PREST_PG_USER=postgres PREST_PG_DATABASE=prest PREST_PG_PORT=5432

before_install:
   - go get -u github.com/kardianos/govendor
   - govendor sync

before_script:
    - psql -c "create database prest;" -U postgres
    - psql prest -c "create table test(name text);" -U postgres
    - psql prest -c "create table test2(name text, number integer);" -U postgres
    - psql prest -c "insert into test (name) values ('prest tester');" -U postgres
    - psql prest -c "insert into test (name) values ('tester02');" -U postgres
    - psql prest -c "insert into test2 (name, number) values ('tester02', 2);" -U postgres

script:
    - sh test.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
