baseurl = "prest.github.io/docs/"
languageCode = "en-us"
metadataformat = "yaml"
title = "pREST"
theme = "hugo-alabaster-theme"

publishDir = "docs"
disqusShortname = ""
googleAnalytics = ""

[params]
	name = "pREST"
	description = "A fully RESTful API from any existing PostgreSQL database."

	github_user   = "prest"
	github_repo   = "prest"
	github_banner = true

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
    logo = "logo.png"


	github_button  = true
	travis_button  = true
	codecov_button = true
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = "[Digitalcraftsman](https://github.com/digitalcraftsman)"
	show_powered_by = true
