version: "3"
services:
    postgres:
        image: postgres
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=prest
            - POSTGRES_DB=prest
            - POSTGRES_PASSWORD=secret
        ports:
            - "6432"
        networks:
            db:
    pgbouncer:
        image: pgbouncer/pgbouncer
        ports:
            - "5432:5432"
        networks:
            db:
        environment:
            - DATABASES_HOST=postgres
            - DATABASES_PORT=6432
            - DATABASES_USER=prest
            - DATABASES_PASSWORD=secret
            - DATABASES_DBNAME=prest
            - PGBOUNCER_LISTEN_PORT=5432
    prest:
        image: prest/prest:v1
        environment:
            - PREST_DEBUG=true # remove comment for enable DEBUG mode (disable JWT)
            - PREST_PG_HOST=postgres
            - PREST_PG_USER=prest
            - PREST_PG_PASS=secret
            - PREST_PG_DATABASE=prest
            - PREST_PG_PORT=5432
            - PREST_JWT_DEFAULT=false # remove if need jwt
        depends_on:
            - postgres
            - pgbouncer
        networks:
            db:
        ports:
            - "3000:3000"
networks:
    db:
