version: "2"
services:
    prest:
        build: .
        links:
            - "postgres:postgres"
        environment:
            - PREST_PG_HOST=postgres
            - PREST_PG_USER=postgres
            - PREST_PG_PASS=prest
            - PREST_PG_DATABASE=prest
            - PREST_PG_PORT=5432
        depends_on:
            - postgres
        ports:
            - "3000:3000"
    postgres:
        build: ./docker/postgres/
        volumes:
            - "./data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=prest
            - POSTGRES_DB=prest